name: PHPStan

on:
    push:
        paths:
            - 'src/**.php'
            - 'tests/**.php'
            - 'config/phpstan.neon'
            - '.github/workflows/phpstan.yml'

jobs:
    test:
        name: "Tests with P${{ matrix.php }} and ${{ matrix.dependencies }} dependencies"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - "8.1"
                    - "8.2"
                    - "8.3"
                dependencies:
                    - "lowest"
                    - "highest"
        steps:
            -   uses: "actions/checkout@v4"
            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
            -   uses: "ramsey/composer-install@v3"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"
                    composer-options: "${{ matrix.composer-options }}"
            -   name: Run PHPStan
                run: ./vendor/bin/phpstan --error-format=github -c ./config/phpstan.neon

